title: "DAGKnight"
description: "Where ancient chivalry meets the futuristic magic of BlockDAG consensus"
url: "https://dagknight.xyz"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
